import Head from 'next/head';
import { Box, Button, Heading } from '@chakra-ui/react';
import React from 'react';

const newProvider = async () => {
  const f = await fetch('/api/providers/create');
  return await f.json();
};

export default function Home() {
  console.log('home')
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box as='main'>
        <Heading as='h1'>Wizyta u barbera w 3 kliknięcia</Heading>
      </Box>
      <Button onClick={() => newProvider()}>nowy</Button>
    </Box>
  );
}
