import Head from 'next/head';
import { Flex, Box, Button, Heading } from '@chakra-ui/react';
import React from 'react';
import Link from 'next/link';

const newProvider = async () => {
  const f = await fetch('/api/providers/create');
  return await f.json();
};
const newAppointment = async () => {
  const f = await fetch('/api/appointments/create');
  return await f.json();
};
const getAvailability = async () => {
  const f = await fetch(
    '/api/appointments/611586d59197e22560b9d2c9/2021-08-18/6115877d9197e22560b9d2d0'
  );
  return await f.json();
};

const newService = async () => {
  const body = {
    name: 'haircut',
    durationInMinutes: 15,
    providerId: '611586d59197e22560b9d2c9',
  };
  const service = await fetch('/api/services/create', {
    method: 'POST',
    body: JSON.stringify(body),
  });
  return await service.json();
};

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex as='main' direction='column'>
        <Heading as='h1'>Kalendarz</Heading>
        <Button onClick={() => newProvider()}>
          nowy użytkownik - service provider
        </Button>
        <Button onClick={() => newAppointment()}>nowa wizyta</Button>
        <Button onClick={() => newService()}>nowa usługa - service</Button>
        <Button onClick={() => getAvailability()}>fetch availability</Button>
        <Link href='/widget/611586d59197e22560b9d2c9'>widget</Link>
      </Flex>
    </Box>
  );
}
