import Head from 'next/head';
import { Box, Button, Heading } from '@chakra-ui/react';
import React from 'react';
import Link from 'next/link';

const newProvider = async () => {
  const f = await fetch('/api/providers/create');
  return await f.json();
};

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box as='main'>
        <Heading as='h1'>Kalendarz</Heading>
      </Box>
      <Button onClick={() => newProvider()}>
        nowy użytkownik - service provider
      </Button>
      <Link href='/widget/6102580d2e0fea34bc7f8fe7'>widget</Link>
    </Box>
  );
}
