import Head from 'next/head';
import { Box, Heading } from '@chakra-ui/react';
import React from 'react';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box as='main'>
        <Heading as='h1'>Wizyta u barbera w 3 kliknięcia</Heading>
      </Box>
    </Box>
  );
}
